PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?knows ?label
WHERE {
 <http://harth.org/andreas/foaf#ah> foaf:knows ?knows .
 ?knows foaf:name ?label .
}