SELECT DISTINCT ?s0 ?joinSO01 ?joinSO00
WHERE{
?joinSO00 <http://rdfs.org/sioc/ns#account_of> <http://s.lnbrg.net/user/3> .
?joinSO01 <http://rdfs.org/sioc/ns#follows> ?joinSO00 .
?s0 <http://xmlns.com/foaf/0.1/account> ?joinSO01 .
}