SELECT ?join1 ?join2 ?join3 
WHERE{
 ?join2 <http://www.w3.org/2002/07/owl#disjointWith> ?join3 .
 ?join1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?join2 .
 <http://my.opera.com/WolfDog09/xml/foaf#me> <http://xmlns.com/foaf/0.1/knows> ?join1 .
}